spring:
  profiles:
    active: work
    include: mysql,eureka
  application:
    name: order8010


server:
  port: 8010


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legendyun.common.entities

logging:
  level:
    tracer: trace
    com.legendyun.payment.dao: DEBUG