mysql:
  url: "localhost:3306/mall-paymentdb"
  username: root
  password: zjy123


eureka-server:
  defaultZone: "http://localhost:8761/eureka" #单机
#  defaultZone: "http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka" #集群

zookeeper:
  url: "192.168.3.119:2181"