spring:
  profiles:
    active: pve
    include: mysql,consul
  application:
    name: payment8001

server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legendyun.payment.entities
logging:
  level:
    tracer: trace
    com.legendyun.payment.dao: DEBUG

