spring:
  profiles:
    active: pve
    include: mysql,zookeeper
  application:
    name: payment8001

server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legendyun.payment.entities
