server:
  port: 8001

spring:
  application:
    name: payment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mall-paymentdb?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowMultiQueries=true
    username: root
    password: zjy123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legendyun.payment.entities